# The edges in this file specify the the flow between the rules

[[edges]]
from = "Returns boolean"
scope = "Parent"
to = ["boolean_literal_cleanup"]

[[edges]]
from = "boolean_literal_cleanup"
scope = "Parent"
to = ["boolean_expression_simplify", "statement_cleanup"]

[[edges]]
from = "boolean_expression_simplify"
scope = "Parent"
to = ["boolean_literal_cleanup"]

[[edges]]
from = "statement_cleanup"
scope = "Parent"
to = [
  "if_cleanup",
  "delete_variable_declaration",
  "delete_field_declaration",
  "remove_parent_assignment",
]

[[edges]]
from = "if_cleanup"
scope = "Parent"
to = ["remove_unnecessary_nested_block"]

[[edges]]
from = "remove_unnecessary_nested_block"
scope = "Parent"
to = ["delete_all_statements_after_return"]

[[edges]]
from = "delete_variable_declaration"
scope = "Method"
to = [
  "replace_identifier_with_value",
  "remove_boolean_assignments_for_variable",
]

[[edges]]
from = "delete_field_declaration"
scope = "Class"
to = [
  "remove_boolean_assignments_for_variable",
  "replace_identifier_with_value",
]

[[edges]]
from = "replace_identifier_with_value"
scope = "Parent"
to = ["boolean_literal_cleanup"]

# Another workflow for inline variable
[[edges]]
from = "remove_parent_assignment"
scope = "Method"
to = ["delete_variable_declaration"]

# Another workflow for inline field
[[edges]]
from = "remove_parent_assignment"
scope = "Class"
to = ["delete_field_declaration"]


