[[edges]]
from = "Returns boolean"
scope = "Parent"
to = ["Boolean literal cleanup"]

[[edges]]
from = "Boolean literal cleanup"
scope = "Parent"
to = ["Boolean expression simplify", "Statement cleanup"]

[[edges]]
from = "Boolean expression simplify"
scope = "Parent"
to = ["Boolean literal cleanup"]

[[edges]]
from = "Statement cleanup"
scope = "Parent"
to = [
  "If cleanup",
  "Inline Local Variable Declaration - Delete variable declaration",
  "Inline Field Declaration - Delete field declaration",
  "Remove assignment-1",
]

[[edges]]
from = "If cleanup"
scope = "Parent"
to = ["Remove unnecesary nested block"]

[[edges]]
from = "Remove unnecesary nested block"
scope = "Parent"
to = ["Elide all statements after return"]

[[edges]]
from = "Inline Local Variable Declaration - Delete variable declaration"
scope = "Method"
to = [
  "Replace identifier with value",
  "Remove assignment",
]

[[edges]]
from = "Inline Field Declaration - Delete field declaration"
scope = "Class"
to = [
  "Remove assignment",
  "Replace identifier with value",
]

[[edges]]
from = "Replace identifier with value"
scope = "Parent"
to = ["Boolean literal cleanup"]


[[edges]]
from = "Remove assignment-1"
scope = "Method"
to = [
  "Inline Local Variable Declaration - Delete variable declaration",
]

[[edges]]
from = "Remove assignment-1"
scope = "Class"
to = [
  "Inline Field Declaration - Delete field declaration"
]


