# The language specific rules in this file are applied after the API specific change has been performed.

# Before : 
#  if (true) { doSomething(); }
# After :
#  { doSomething(); } 
# 
# Before : 
#  if (true) { doSomething(); } else { doSomethingElse();}
# After :
#  { doSomething(); } 
#
[[rules]]
name = "simplify_if_statement_true"
query = """
(
    (if_statement
        condition : ((parenthesized_expression ((true) @i)))
        consequence : ((statement) @consequence))
@if_statement)
"""
replace_node = "if_statement"
replace = "@consequence"
groups = ["if_cleanup"]

# Before : 
#  if (true) { doSomething(); } else { doSomethingElse();}
# After :
#  { doSomethingElse(); } 
#
# Before : 
#  if (true) { doSomething(); }
# After :
#  
[[rules]]
name = "simplify_if_statement_false"
query = """
(
    (if_statement
        condition : ((parenthesized_expression ((false) @i)))
        consequence : ((statement) @consequence)
        alternative : ((_) @alternative) ?)
@if_statement)"""
replace_node = "if_statement"
replace = "@alternative"
groups = ["if_cleanup"]

# Before : 
#  !false
# After :
#  true 
#
[[rules]]
name = "simplify_not_false"
query = """
(
    (unary_expression
        operator: "!"
        operand: (false))
@unary_expression)
"""
replace_node = "unary_expression"
replace = "true"
groups = ["boolean_expression_simplify"]


# Before : 
#  !true
# After :
#  false
#
[[rules]]
name = "simplify_not_true"
query = """
(
    (unary_expression
        operator: \"!\"
        operand: (true))
@u)
"""
replace_node = "u"
replace = "false"
groups = ["boolean_expression_simplify"]


# Before : 
#  {
#     someStepsBefore();
#     {
#        someSteps();
#     }   
#     someStepsAfter();
#  }
# After :
#  {
#     someStepsBefore();
#        someSteps();
#     someStepsAfter();
#  }
#
[[rules]]
name = "remove_unnecessary_nested_block"
query = """
((block
        (
            (_)* @pre
            (block (_)* @nested.statements) @nested.block
            (_)* @post
        )
    )@sb)"""
replace_node = "nested.block"
replace = "@nested.statements"

# Before : 
#  true && abc()
# After :
#  abc()
#
[[rules]]
name = "simplify_true_and_something"
query = """
(
    (binary_expression
        left: (true)
        operator:"&&"
         right : (_)* @rhs )
) @binary_expression"""
replace_node = "binary_expression"
replace = "@rhs"
groups = ["boolean_expression_simplify"]

# Before : 
#  abc() && true
# After :
#  abc()
#
[[rules]]
name = "simplify_something_and_true"
query = """
(
    (binary_expression
        left : (_)* @lhs
        operator:"&&"
        right: (true)
    )
@binary_expression)"""
replace_node = "binary_expression"
replace = "@lhs"
groups = ["boolean_expression_simplify"]

# Before : 
#  false && abc()
# After :
#  false
#
[[rules]]
name = "simplify_false_and_something"
query = """
(
    (binary_expression
        left: (false)
        operator : "&&"
        right : (_)* @rhs
    )
@binary_expression)"""
replace_node = "binary_expression"
replace = "false"
groups = ["boolean_expression_simplify"]

# Before : 
#  abc() && false
# After :
#  false
#
[[rules]]
name = "simplify_something_and_false"

query = """
(
    (binary_expression
        left : (_)* @lhs
        operator : "&&"
        right: (false)
    )
@binary_expression)
"""
replace_node = "binary_expression"
replace = "false"
groups = ["boolean_expression_simplify"]


# Before : 
#  abc() || true
# After :
#  true
#
[[rules]]
name = "simplify_something_or_true"
query = """
(
    (binary_expression
        left : (_)* @lhs
        operator:"||"
        right: (true)
    )
@binary_expression)"""
replace_node = "binary_expression"
replace = "true"
groups = ["boolean_expression_simplify"]

# Before : 
#  true || abc()
# After :
#  true
#
[[rules]]
name = "simplify_true_or_something"
query = """
(
    (binary_expression
        left : (true)
        operator:"||"
        right: (_)* @rhs
    )
@binary_expression)
"""
replace_node = "binary_expression"
replace = "true"
groups = ["boolean_expression_simplify"]


# Before: 
#  abc() || false
# After :
#  abc()
#
[[rules]]
name = "simplify_something_or_false"
query = """(
(
    binary_expression
        left : (_)* @lhs
        operator:"||"
        right: (false)
    )
@binary_expression)"""
replace_node = "binary_expression"
replace = "@lhs"
groups = ["boolean_expression_simplify"]

# Before: 
#  false || abc()
# After :
#  abc()
#
[[rules]]
name = "simplify_false_or_something"
query = """
(
    (binary_expression
        left : (false)
        operator:"||"
        right: (_)* @rhs
    )
@binary_expression)"""
replace_node = "binary_expression"
replace = "@rhs"
groups = ["boolean_expression_simplify"]

# Before :
#  {
#    something();
#    return 10;
#    somethingMore();  
#    return 100;
#    
#  } 
# After :
#  {
#    something();
#    return 10;
#  } 
#
[[rules]]
name = "delete_all_statements_after_return"
query = """(
        (block  ((statement)* @pre)
         ((return_statement) @r)
         ((statement)+ @post)) @b)"""
replace_node = "post"
replace = ""

# Before :
#  true ? abc() : def();
# After :
#  abc()
#
[[rules]]
name = "simplify_ternary_operator_true"
query = """
(
    (ternary_expression condition: (true)
        consequence: (_)* @consequence
        alternative: (_)* @alternative)
@ternary_expression)"""
replace_node = "ternary_expression"
replace = "@consequence"
groups = ["if_cleanup"]

# Before :
#  false ? abc() : def();
# After :
#  def()
#
[[rules]]
name = "simplify_ternary_operator_false"
query = """
(
    (ternary_expression condition: (false)
        consequence: (_)* @consequence
        alternative: (_)* @alternative)
@ternary_expression)"""
replace_node = "ternary_expression"
replace = "@alternative"
groups = ["if_cleanup"]

# Before :
# public foo someMethod() { 
#  boolean isFlag = true; 
#  somethingElse();
# }
#  
# After :
# public foo someMethod() { 
#  somethingElse();
# }
#
# Note: Due to the constraint the below example is not updated
# Before :
# public foo someMethod() { 
#  boolean isFlag = true; 
#  isFlag = getFlagStatus();
#  somethingElse();
# }
#  
# After :
# public foo someMethod() { 
#  boolean isFlag = true; 
#  isFlag = getFlagStatus();
#  somethingElse();
# }
#
[[rules]]
name = "delete_variable_declaration"
query = """
(
((local_variable_declaration 
				declarator: (variable_declarator 
                					name: (_) @variable_name
                					value: [(true) (false)] @init)) @variable_declaration)
)
"""
replace_node = "variable_declaration"
replace = ""
groups = []
# Check if there is no assignment where the variable @variable_name is 
# assigned to a value other than @init, within the method body
[rules.constraint]
matcher = "(method_declaration) @md"
predicate = "None"
queries = ["""
(
((assignment_expression
    				left: (_) @a.lhs
                    right: (_) @a.rhs) @a)
(#eq? @a.lhs "@variable_name")
(#not-eq? @a.rhs "@init")
)"""]

# Same as the rule `delete_variable_declaration`, but applicable to 
# fields. 
[[rules]]
name = "delete_field_declaration"
query = """
(
((field_declaration 
				declarator: (variable_declarator 
                					name: (_) @variable_name
                					value: [(true) (false)] @init)) @field_declaration)
)
"""
replace_node = "field_declaration"
replace = ""
groups = []
# Check if there is no assignment where the variable @variable_name is 
# assigned to a value other than @init, within the method body
[rules.constraint]
matcher = "(class_declaration) @cd"
predicate = "None"
queries = ["""(
((assignment_expression
    				left: (_) @a.lhs
                    right: (_) @a.rhs) @a)
(#eq? @a.lhs "@variable_name")
(#not-eq? @a.rhs "@init")
)"""]

[[rules]]
name = "remove_boolean_assignments_for_variable"
query = """
(
(expression_statement (assignment_expression
                                left: (_) @l
                    right: (_) @r)) @expression_statement
(#eq? @l "@variable_name")
(#eq? @r "@init")
) 
"""
replace_node = "expression_statement"
replace = ""
groups = []
holes = ["variable_name", "init"]

# remove_boolean_assignments_for_variable if it is the only assignment in the entire class.
[[rules]]
name = "remove_parent_assignment"
query = """
(
(expression_statement (assignment_expression
                                left: (_) @variable_name
                    right: (_) @init)) @expression_statement
) 
"""
replace_node = "expression_statement"
replace = ""
groups = []
holes = []
[rules.constraint]
matcher = "(class_declaration) @cd"
predicate = "None"
queries = ["""(
((assignment_expression
    				left: (_) @a.lhs
                    right: (_) @a.rhs) @a)
(#eq? @a.lhs "@variable_name")
(#not-eq? @a.rhs "@init")
)"""]

# Replaces the identifier with the name @variable_name with value @init
# Let's say @variable_name = `x` and @init = `true`
# Before :
#  if (x  && abc()) { doSomething(); }
# After 
#  if (true  && abc()) { doSomething(); } 
#
[[rules]]
name = "replace_identifier_with_value"
query = """
(
(identifier) @identifier
(#eq? @identifier "@variable_name")
)
"""
replace_node = "identifier"
replace = "@init"
groups = []
holes = ["variable_name", "init"]


# Dummy rule that acts as a junction for all boolean based cleanups
[[rules]]
name = "boolean_literal_cleanup"
query = """
"""
replace_node = ""
replace = ""

# Dummy rule that acts as a junction for all statement based cleanups
[[rules]]
name = "statement_cleanup"
query = """
"""
replace_node = ""
replace = ""
