[[rules]]
name = "Simple If-(optional)else True"
query = """
(
((navigation_expression suffix: (_) @s ) @n)
((call_suffix (value_arguments (value_argument 
									name: (_) @e
                                    value: (navigation_expression suffix: (_) @s1)))) @c)
(#eq? @s ".isTreated")
(#eq? @s1 ".@stale_flag_name")
)

"""
replace_node = "ifstmt"
replace = "@s"
groups = ["If cleanup", "Statement cleanup"]