[[edges]]
from = "Returns boolean"
scope = "Parent"
to = "Boolean expression cleanup"

[[edges]]
from = "Returns boolean"
scope = "Parent"
to = "Statement cleanup"

[[edges]]
from = "Returns boolean"
scope = "Parent"
to = "Inline Local Variable Declaration - Delete variable declaration"

[[edges]]
from = "Returns boolean"
scope = "Parent"
to = "Inline Field Declaration - Delete field declaration"


[[edges]]
from = "Returns boolean"
scope = "Parent"
to = "Remove assignment-1"


#####################################################################

[[edges]]
from = "Boolean expression cleanup"
scope = "Parent"
to = "Boolean expression cleanup"

[[edges]]
from = "If cleanup"
scope = "Parent"
to = "Block cleanup"


[[edges]]
from = "Inline Local Variable Declaration - Delete variable declaration"
scope = "Method"
to = "Replace identifier with value"


[[edges]]
from = "Inline Local Variable Declaration - Delete variable declaration"
scope = "Method"
to = "Remove assignment"


[[edges]]
from = "Inline Field Declaration - Delete field declaration"
scope = "Class"
to = "Remove assignment"

[[edges]]
from = "Remove assignment-1"
scope = "Method"
to = "Inline Local Variable Declaration - Delete variable declaration"


[[edges]]
from = "Remove assignment-1"
scope = "Class"
to = "Inline Field Declaration - Delete field declaration"


[[edges]]
from = "Inline Field Declaration - Delete field declaration"
scope = "Class"
to = "Replace identifier with value"

[[edges]]
from = "Replace identifier with value"
scope = "Parent"
to = "Boolean expression cleanup"

[[edges]]
from = "Replace identifier with value"
scope = "Parent"
to = "If cleanup"

[[edges]]
from = "Remove unnecesary nested block"
scope = "Parent"
to = "Elide all statements after return"
