# The edges in this file specify the the flow between the rules
[[edges]]
from = "delete_flag_method_declaration_fully_annotated"
scope = "Global"
to = [
  "replace_flag_method_with_boolean_literal",
  "delete_put",
]

[[edges]]
from = "delete_flag_method_declaration_inside_annotated_interface"
scope = "Global"
to = [
  "replace_flag_method_with_boolean_literal",
  "delete_put",
]