[[edges]]
from = "Interface based, annotated method declaration"
scope = "Global"
to = [
  "Interface based, replace method invocation chain with true/false",
  "Interface based, method invocation, put",
]

[[edges]]
from = "Interface based, annotated method declaration and interface"
scope = "Global"
to = [
  "Interface based, replace method invocation chain with true/false",
  "Interface based, method invocation, put",
]