[[edges]]
from = "Interface based, annotated method declaration"
scope = "Global"
# populate_holes = ["[@m_name]", "@m_name"]
to = "Interface based, replace method invocation chain with true/false"

[[edges]]
from = "Interface based, annotated method declaration and interface"
scope = "Global"
# populate_holes = ["[@m_name]", "@m_name"]
to = "Interface based, replace method invocation chain with true/false"
