# This file contains rules to the specifc feature flag API.

#
# For @stale_flag_name = STALE_FLAG and @treated = true
# Before 
#  exp.isToggleEnabled(Expriement.STALE_FLAG)
# After 
#  true
#
[[rules]]
name = "Enum Based, toggle enabled"
query = """((
	(method_invocation 
    	name : (_) @name
        arguments: ((argument_list 
        				([
                          (field_access field: (_)@argument)
                          (_) @argument
                         ])) )
        	
    ) @method_invocation
)
(#eq? @name "isToggleEnabled")
(#eq? @argument "@stale_flag_name")
)"""
replace_node = "method_invocation"
replace = "@treated"
groups = [ "Returns boolean"]
holes = ["treated", "stale_flag_name"]

#
# For @stale_flag_name = STALE_FLAG and @treated = true
# Before :
#  exp.isFlagTreated(STALE_FLAG)
# After :
#  true
#
[[rules]]
name = "Enum Based, flag enabled"
query = """((
	(method_invocation 
    	name : (_) @name
        arguments: ((argument_list 
        				([
                          (field_access field: (_)@argument)
                          (_) @argument
                         ])) )
        	
    ) @method_invocation
)
(#eq? @name "isFlagTreated")
(#eq? @argument "@stale_flag_name")
)"""
replace_node = "method_invocation"
replace = "@treated"
groups = [ "Returns boolean"]
holes = ["treated", "stale_flag_name"]

#
# For @stale_flag_name = STALE_FLAG and @treated = true
# Before :
#  exp.isToggleDisabled(STALE_FLAG)
# After :
#  false
#
[[rules]]
name = "Enum Based, toggle disabled"
query = """((
	(method_invocation 
    	name : (_) @name
        arguments: ((argument_list 
        				([
                          (field_access field: (_)@argument)
                          (_) @argument
                         ])) )
        	
    ) @method_invocation
)
(#eq? @name "isToggleDisabled")
(#eq? @argument "@stale_flag_name")
)"""
replace_node = "method_invocation"
replace = "@treated_complement"
groups = [ "Returns boolean"]
holes = ["treated_complement", "stale_flag_name"]

#
# For @stale_flag_name = STALE_FLAG 
# Before :
#  enum Flags {
#   ABC, STALE_FLAG, OTHER_FLAG	
#  }
# After :
#  enum Flags {
#   ABC, OTHER_FLAG	
#  }
#
[[rules]]
name = "Enum based, Delete enum constant"
query = """
    (
    ((enum_constant name : (_) @n) @ec)       
    (#eq? @n  "@stale_flag_name")
    )
    """
replace_node = "ec"
replace = ""
groups = []
holes = ["stale_flag_name"]

#
# For @stale_flag_name = STALE_FLAG and @treated = true
# Before :
#   exp.putToggleEnabled(STALE_FLAG);
# After :
#   
#
[[rules]]
name = "Enum based, method invocation, put enabled"
query = """
(
(expression_statement (method_invocation name : (_) @name
					arguments: (argument_list
                    			([
		                          (field_access field: (_)@argument)
        		                  (_) @argument
                		         ])))) @expression_statement
 (#eq? @name "putToggleEnabled")
 (#eq? @argument "@stale_flag_name")
)
"""
replace_node = "expression_statement"
replace = ""
groups = []
holes = ["stale_flag_name"]

#
# For @stale_flag_name = STALE_FLAG and @treated = true
# Before :
#   exp.putToggleDisabled(STALE_FLAG);
# After :
#   
#
[[rules]]
name = "Enum based, method invocation, put disabled"
query = """
(
(expression_statement (method_invocation name : (_) @name
					arguments: (argument_list
                    			([
		                          (field_access field: (_)@argument)
        		                  (_) @argument
                		         ])))) @expression_statement
 (#eq? @name "putToggleDisabled")
 (#eq? @argument "@stale_flag_name")
)
"""
replace_node = "expression_statement"
replace = ""
groups = []
holes = ["stale_flag_name"]

#
# For @stale_flag_name = STALE_FLAG and @treated = true
# Before :
#   exp.includeEvent(STALE_FLAG);
# After :
#   
#
[[rules]]
name = "Enum based, method invocation, includeEvent"
query = """
(
(expression_statement (method_invocation name : (_) @name
					arguments: (argument_list
                    			([
		                          (field_access field: (_)@argument)
        		                  (_) @argument
                		         ])))) @expression_statement
 (#eq? @name "includeEvent")
 (#eq? @argument "@stale_flag_name")
)
"""
replace_node = "expression_statement"
replace = ""
groups = []
holes = ["stale_flag_name"]

# 
# interface IExp {
#  @BoolParam(key = "STALE_FLAG", namespace="NS")	
#  public void isStaleFeature();
#  @BoolParam(key = "OTHER_FLAG", namespace="NS")
#  public void isOtherFeature();
# }
#
# interface IExp {
#  @BoolParam(key = "OTHER_FLAG", namespace="NS")
#  public void isOtherFeature();
# }
#
[[rules]]
name = "Interface based, annotated method declaration"
query = """
(
(method_declaration
	 (modifiers (annotation
     				name: (_) @annotation_name
					arguments: (annotation_argument_list
                    	(element_value_pair
							 key: (_) @k1
							 value: (_) @v1))))
      name: (_) @m_name
 )@method_declaration
 (#eq? @annotation_name "BoolParam")
 (#eq? @k1 "key")
 (#eq? @v1 "\\\"@stale_flag_name\\\"")
 )
 (
(method_declaration
	 (modifiers (annotation
					arguments: (annotation_argument_list
                    	(element_value_pair
							 key: (_) @k2
							 value: (_) @v2))))
 )@m2
 (#eq? @k2 "namespace")
 (#eq? @v2 "\\\"@namespace\\\"")
 )
"""
replace_node = "method_declaration"
replace = ""
groups = ["Delete Method"]
holes = ["stale_flag_name", "namespace"]

# Before :
#  @ParamDefinition(namespace="NS")
#  interface IExp {
#   @BoolParam(key = "STALE_FLAG")	
#   public void isStaleFeature();
#   @BoolParam(key = "OTHER_FLAG", namespace="Some_NS")
#   public void isOtherFeature();
#  }
# After :
#  interface IExp {
#   @BoolParam(key = "OTHER_FLAG", namespace="Some_NS")
#   public void isOtherFeature();
#  }
#
[[rules]]
name = "Interface based, annotated method declaration and interface"
query= """
(
(interface_declaration
	(modifiers (annotation
     				name: (_) @a_name
					arguments: (annotation_argument_list
                    	(element_value_pair
							 key: (_) @k1
							 value: (_) @v1)))) @mod
    name: (_) @i_name
	body: (interface_body
    	(_)* @pre
    	(method_declaration
			 (modifiers (annotation
					arguments: (annotation_argument_list
                    	(element_value_pair
							 key: (_) @k2
							 value: (_) @v2))))
                             
        name: (_) @m_name) @md
	    (_)* @post
    )
) @id
 (#eq? @a_name "ParameterDefinition")
 (#eq? @k1 "namespace")
 (#eq? @v1 "\\\"@namespace\\\"")
 (#eq? @k2 "key")
 (#eq? @v2 "\\\"@stale_flag_name\\\"")
)
"""
replace_node = "md"
replace = ""
groups = ["Delete Method"]
holes = ["stale_flag_name", "namespace"]

# For @m_name = `isStaleFeature`, @treated = `true`
# Before :
#  exp.isStaleFeature().getCachedValue()
# After: 
#  true
#
[[rules]]
name = "Interface based, replace method invocation chain with true/false"
query = """
(
   ((method_invocation
       object: (method_invocation 
       			object: (_) @receiver
       			name: (identifier) @nested_name)
       name : (identifier) @name) 
       @method_invocation)
   (#eq? @name "getCachedValue")
   (#eq? @nested_name "@m_name")
   (#not-match? @receiver "^[A-Z]+.*")
)"""
replace_node = "method_invocation"
replace = "@treated"
groups = ["Returns boolean"]
holes = ["m_name", "treated"]

# For @m_name = `isStaleFeature`, @treated = `true`
# Before : 
# cp.put(e.isStaleFeature(), true);
# After : 
# 
#
[[rules]]
name = "Interface based, method invocation, put"
query = """
(
(expression_statement ((method_invocation name: (_) @n
			arguments : (
            (argument_list 
            	(method_invocation 
                		name: (_) @an)
                ([(true) (false)])
             ))

            ) @m) ) @expression_statement
 (#eq? @n "put")
 (#eq? @an "@m_name")
)
"""
replace_node = "expression_statement"
replace = ""
groups = []
holes = ["m_name"]

#
# For @stale_flag_name = `STALE_FLAG`, @treated = `true`
# Before : 
#  @Pval(name = "STALE_FLAG", namespace= "ns", val = true)
#  void someTestMethod() {
#   // Test code 
#  }
# After :
#  void someTestMethod() {
#   // Test code 
#  }
#
[[rules]]
name = "Delete annotated method, treated"
query = """(
(method_declaration
	(modifiers (annotation name: (_) @n
    					  arguments : 
                          	(annotation_argument_list
                            	(element_value_pair 
                                	key : (_) @k1
                                    value : (_) @v1))) )) @md1
(#eq? @k1 "ns")
(#eq? @v1 "\\\"@namespace\\\"")
(#eq? @n "ParameterValue")
)
(
(method_declaration
	(modifiers (annotation name: (_) 
    					  arguments : 
                          	(annotation_argument_list
                            	(element_value_pair 
                                	key : (_) @k2
                                    value : (_) @v2))))) @md2
(#eq? @k2 "key")
(#eq? @v2 "\\\"@stale_flag_name\\\"")
)
(
(method_declaration
	(modifiers (annotation name: (_) 
    					  arguments : 
                          	(annotation_argument_list
                            	(element_value_pair 
                                	key : (_) @k3
                                    value : (_) @v3))) @an) ) @md3
(#eq? @k3 "val")
(#eq? @v3 "\\\"@treated\\\"")
)"""
replace_node = "an"
replace = ""
groups = []
holes = ["stale_flag_name", "treated", "namespace"]

#
# For @stale_flag_name = `STALE_FLAG`, @treated = `true`
# Before : 
#  @Pval(name = "STALE_FLAG", namespace= "ns", val = false)
#  void someTestMethod() {
#   // Test code 
#  }
# After :
# 
#
[[rules]]
name = "Delete annotated method, not treated"
query = """(
(method_declaration
	(modifiers (annotation name: (_) @n
    					  arguments : 
                          	(annotation_argument_list
                            	(element_value_pair 
                                	key : (_) @k1
                                    value : (_) @v1))) )) @md1
(#eq? @k1 "ns")
(#eq? @v1 "\\\"@namespace\\\"")
(#eq? @n "ParameterValue")
)
(
(method_declaration
	(modifiers (annotation name: (_) 
    					  arguments : 
                          	(annotation_argument_list
                            	(element_value_pair 
                                	key : (_) @k2
                                    value : (_) @v2))))) @md2
(#eq? @k2 "key")
(#eq? @v2 "\\\"@stale_flag_name\\\"")
)
(
(method_declaration
	(modifiers (annotation name: (_) 
    					  arguments : 
                          	(annotation_argument_list
                            	(element_value_pair 
                                	key : (_) @k3
                                    value : (_) @v3))) @an) ) @md3
(#eq? @k3 "val")
(#eq? @v3 "\\\"@treated_complement\\\"")
)"""
replace_node = "md3"
replace = ""
groups = ["Delete Method"]
holes = ["stale_flag_name", "treated_complement", "namespace"]