name: Release Polyglot Piranha
on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz
          - target: x86_64-apple-darwin
            archive: zip
    steps:
      # - uses: actions/checkout@master
      # - name: Compile and release rust library
      #   uses: rust-build/rust-build.action@v1.3.2
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     RUSTTARGET: ${{ matrix.target }}
      #     ARCHIVE_TYPES: ${{ matrix.archive }}
      #     SRC_DIR: polyglot/piranha
      #     args: --no-default-features
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          SRC_DIR: polyglot/piranha
      - name: Release with Maturin
        uses: messense/maturin-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          maturin-version: latest
          target: ${{ matrix.target }}
          command: build
          args: --release
          SRC_DIR: polyglot/piranha
