name: Rust CI
on:
  pull_request:
  push: 
    branches:
      - master
env:
  CARGO_TERM_COLOR: always
jobs:
  defaults:
    run:
      shell: bash
      working-directory: generic/piranha-tree-sitter
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install-Tree-Sitter
        run: cargo install tree-sitter-cli
      - name: Format the code
        run: cargo fmt 
        working-directory: generic/piranha-tree-sitter
      - name: Test
        run: cargo test
        working-directory: generic/piranha-tree-sitter
        env:
          RUST_LOG: warn